name: Build iOS Tweak

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Theos Environment
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=~/theos" >> $GITHUB_ENV
        
    - name: Download iOS SDK
      run: |
        curl -LO https://github.com/theos/sdks/releases/latest/download/iPhoneOS16.5.sdk.tar.xz
        tar -xf iPhoneOS16.5.sdk.tar.xz -C ~/theos/sdks/
        
    - name: Compile Dylib
      run: |
        make package FINALPACKAGE=1
        
    - name: Upload Compiled Binary
      uses: actions/upload-artifact@v4
      with:
        name: MetalFXStub-Dylib
        path: .theos/obj/debug/*.dylib
